### ISSUE TITLE
When I hovered svg I can't change it color 

### ISSUE THREAD

**Issue by yaxshi-foydalanuvchi** [davronkhamdamov/ci-cd-practice#1]
# I can't fix that
```css
div:hover {
    background: black;
}

svg path {
    transition: 0.5s;
}

div:hover svg path {
    fill: red;
}
```

**Comment by davronkhamdamov** [comment]
> # I can't fix that
> ```css
> div:hover {
>     background: black;
> }
> 
> svg path {
>     transition: 0.5s;
> }
> 
> div:hover svg path {
>     fill: red;
> }
> ```
```css
div:hover svg path {
    fill: blue;
}
```
xato qilma
